/**
 * All story prompts from the Story Portal
 */

export const ALL_PROMPTS = [
  'A love story',
  'When someone was a friend to me',
  'My first time',
  'When I fell in love',
  'Most tender moment of my life...',
  'When I see the world with eyes of love',
  'Dreams',
  'Eye of the Tiger!!',
  'A leap of faith',
  'When it all changed for me',
  'Overcoming Fear',
  'Ghost Story!',
  'Near death experience',
  'And then I got caught',
  'When I got away with it',
  'This one time at the Burn',
  "That's gross!",
  'Unexpected bodily function',
  'I was so embarrassed',
  'Drunken stupidity & hilarity',
  'Bamboozled!',
  'Conception',
  'My birth story',
  'When I was little',
  'High school was',
  'Something I grew out of',
  'If I knew then what I know now',
  'The wisdom that lives in me says',
  'What I learned from hard times',
  'A song that holds a memory for me',
  'Breakdown to breakthrough',
  'A funeral',
  'If I could speak to someone passed on',
  "You're Fired!",
  'Job Interview',
  'Epic fail',
  'A Tall Tale',
  'An epic adventure',
  'Crazy psychedelic trip',
  'Triumph!',
  'A trailblazer I met',
  'A star encounter',
  'Someone who taught me something',
  'Someone I admire',
  'Something I do really well',
  'Yeah, I suck at that',
  'My 5 minutes of fame',
  'How I got my million dollar idea',
  'When I told the truth',
  'When time stood still',
  'All in the family',
  'Mothers',
  'Fathers',
  'Sisters and brothers',
  'My first concert experience',
  'My relationship with my body',
  'What I love most about myself',
  'What makes me different',
  'Surprise!',
  'Close call',
  'When I look in the mirror',
  'Confession opportunity!',
  'This one time in the Port-o-Potty',
  'Animals!',
  'Nothing is forever, or is it?',
  'Getting lost',
  'A miracle',
  'The home I grew up in',
  'One of the best days of my life',
  'A missed connection',
  'Best halloween experience',
  'A time I really appreciated women',
  'A time I really appreciated men',
  'A nickname and how I got it',
  'What are you so afraid of?',
  'My favorite achievement so far',
  'How I got this scar',
  'If I were braver than I am now',
  "Regrets, I've had a few, but then again",
  "The story I'm most afraid of telling",
  'When I took it to the limit',
  'Sweet 16',
  'Just in time',
  "Closest to paradise I've ever been",
  'When trust paid off',
  'A blast from the past',
  'Danger',
  'Remarkable courage',
  'What I want to be remembered or known for',
  'My Sanctuary',
  'What is your "catch phrase?"',
  'A decision I made',
  "Something I can't live without",
  'I had an idea',
  'That shit was crazy!',
  'I had no idea',
  'And then, I transcended',
  'The best meal ever!',
  'Stickin it to the Man!',
  'Harsh reality made silly',
  'I was in stitches',
  'If I won the lottery',
  'Awakening',
  'What matters to me',
  'Deja vu',
  'A very weird dream',
  'Serendipitous Synchronicity',
  "I'll never forget it",
  'All about Dad',
  'All about Mom',
  'Just make that shit up!',
  'An unexpected meeting',
  'Freak of Nature',
  'If I could have one superpower',
  'Outlandish Sex Acts',
  'Tear Jerker',
  'God is',
  "Grandma's Cookin'",
  'My Favorite Pet',
  'It was so GREAT, and then it was over.',
  'It Made No Sense',
  'My idea of a good time',
  'Over my head',
  'Beauty Secrets',
  'My Personal Hell',
  'Silence',
  'My Personal Heaven',
  'Letting go',
  'Secret Fetish',
  'Today is not Yesterday',
  'What Makes Me Come Alive',
  'I was dreaming',
  'Anywhere in the World',
  'Best Sex Ever',
  'I Shit My Pants When',
  'An Intelligent Contribution',
  'Something that Fascinates Me',
  'What Turns Me On',
  'My Fairy Tale',
  'How Did I Get Here?',
  'Epiphany',
  'What Grinds My Gears',
];

// Get all prompts with 24+ characters for testing
export const LONG_PROMPTS = ALL_PROMPTS.filter((p) => p.length >= 24);

// Test batches for development
export const TEST_BATCH_1 = LONG_PROMPTS.slice(0, 20);
export const TEST_BATCH_2 = LONG_PROMPTS.slice(20, 40);
