"""
L14 Skill Library - Skill Models

Defines the data models for skills, skill definitions, and validation results.
Skills are agent-specific instruction files that provide role context, responsibilities,
and procedural knowledge for Claude Code agents.
"""

from pydantic import BaseModel, Field
from typing import Dict, Any, Optional, List
from datetime import datetime
from uuid import UUID, uuid4
from enum import Enum


# =============================================================================
# Skill File Schema/Template
# =============================================================================

SKILL_FILE_SCHEMA = {
    "version": "1.0.0",
    "description": "Schema for Claude Code skill files",
    "required_sections": [
        "metadata",
        "role",
        "responsibilities",
    ],
    "optional_sections": [
        "tools",
        "procedures",
        "examples",
        "constraints",
        "dependencies",
    ],
    "template": '''---
# Skill File v1.0
# Generated by L14 Skill Library

metadata:
  skill_id: "{skill_id}"
  name: "{name}"
  version: "{version}"
  created_at: "{created_at}"
  updated_at: "{updated_at}"
  author: "{author}"
  tags: {tags}
  priority: {priority}

role:
  title: "{role_title}"
  description: |
    {role_description}
  expertise_areas:
    {expertise_areas}

responsibilities:
  primary:
    {primary_responsibilities}
  secondary:
    {secondary_responsibilities}

tools:
  required:
    {required_tools}
  optional:
    {optional_tools}

procedures:
  {procedures}

examples:
  {examples}

constraints:
  token_budget: {token_budget}
  max_context_tokens: {max_context_tokens}
  execution_timeout_seconds: {execution_timeout}

dependencies:
  skills:
    {dependent_skills}
  services:
    {dependent_services}
---
''',
}

SKILL_FILE_TEMPLATE = SKILL_FILE_SCHEMA["template"]


class SkillStatus(str, Enum):
    """Skill status enum."""
    DRAFT = "draft"
    ACTIVE = "active"
    DEPRECATED = "deprecated"
    ARCHIVED = "archived"


class SkillPriority(str, Enum):
    """Skill priority for loading order."""
    CRITICAL = "critical"     # Always load first (core identity)
    HIGH = "high"            # Load for most operations
    MEDIUM = "medium"        # Load when relevant
    LOW = "low"              # Load only when specifically needed
    OPTIONAL = "optional"    # User-requested only


class SkillCategory(str, Enum):
    """Skill category for organization."""
    CORE = "core"            # Core agent identity
    TECHNICAL = "technical"  # Technical skills
    DOMAIN = "domain"        # Domain-specific knowledge
    PROCEDURAL = "procedural"  # Step-by-step procedures
    TOOL = "tool"            # Tool usage skills
    INTEGRATION = "integration"  # Service integration skills
    COMMUNICATION = "communication"  # User interaction skills


# =============================================================================
# Skill Definition Models
# =============================================================================

class SkillMetadata(BaseModel):
    """Metadata for a skill file."""
    skill_id: UUID = Field(default_factory=uuid4, description="Unique skill identifier")
    name: str = Field(..., description="Skill name")
    version: str = Field(default="1.0.0", description="Skill version")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    author: str = Field(default="L14_skill_library", description="Skill author")
    tags: List[str] = Field(default_factory=list, description="Skill tags for categorization")
    priority: SkillPriority = Field(default=SkillPriority.MEDIUM)
    category: SkillCategory = Field(default=SkillCategory.TECHNICAL)
    token_count: int = Field(default=0, description="Estimated token count of skill file")


class SkillRole(BaseModel):
    """Role definition within a skill."""
    title: str = Field(..., description="Role title")
    description: str = Field(..., description="Role description")
    expertise_areas: List[str] = Field(default_factory=list, description="Areas of expertise")


class SkillResponsibilities(BaseModel):
    """Responsibilities defined in a skill."""
    primary: List[str] = Field(default_factory=list, description="Primary responsibilities")
    secondary: List[str] = Field(default_factory=list, description="Secondary responsibilities")


class SkillTools(BaseModel):
    """Tool requirements for a skill."""
    required: List[str] = Field(default_factory=list, description="Required tools")
    optional: List[str] = Field(default_factory=list, description="Optional tools")


class SkillProcedure(BaseModel):
    """A procedure or workflow within a skill."""
    name: str = Field(..., description="Procedure name")
    description: str = Field(..., description="What the procedure does")
    trigger: Optional[str] = Field(None, description="When to invoke this procedure")
    steps: List[str] = Field(default_factory=list, description="Ordered steps")


class SkillExample(BaseModel):
    """An example interaction for a skill."""
    name: str = Field(..., description="Example name")
    description: Optional[str] = Field(None, description="Example description")
    user_input: str = Field(..., description="Example user input")
    expected_response: str = Field(..., description="Expected agent response")


class SkillConstraints(BaseModel):
    """Constraints for skill execution."""
    token_budget: int = Field(default=2000, description="Token budget for this skill")
    max_context_tokens: int = Field(default=8000, description="Max tokens in context")
    execution_timeout_seconds: int = Field(default=300, description="Execution timeout")


class SkillDependencies(BaseModel):
    """Dependencies for a skill."""
    skills: List[str] = Field(default_factory=list, description="Dependent skill IDs")
    services: List[str] = Field(default_factory=list, description="Required services")


class SkillDefinition(BaseModel):
    """
    Complete skill definition structure.

    This represents the full structure of a skill file that can be
    generated, validated, and used by agents.
    """
    metadata: SkillMetadata
    role: SkillRole
    responsibilities: SkillResponsibilities
    tools: SkillTools = Field(default_factory=SkillTools)
    procedures: List[SkillProcedure] = Field(default_factory=list)
    examples: List[SkillExample] = Field(default_factory=list)
    constraints: SkillConstraints = Field(default_factory=SkillConstraints)
    dependencies: SkillDependencies = Field(default_factory=SkillDependencies)

    class Config:
        from_attributes = True


# =============================================================================
# CRUD Models
# =============================================================================

class SkillCreate(BaseModel):
    """Request model for creating a new skill."""
    name: str = Field(..., description="Skill name")
    role_title: str = Field(..., description="Role title for the skill")
    role_description: str = Field(..., description="Role description")
    expertise_areas: List[str] = Field(default_factory=list)
    primary_responsibilities: List[str] = Field(default_factory=list)
    secondary_responsibilities: List[str] = Field(default_factory=list)
    required_tools: List[str] = Field(default_factory=list)
    optional_tools: List[str] = Field(default_factory=list)
    tags: List[str] = Field(default_factory=list)
    priority: SkillPriority = Field(default=SkillPriority.MEDIUM)
    category: SkillCategory = Field(default=SkillCategory.TECHNICAL)
    token_budget: int = Field(default=2000)
    author: Optional[str] = None


class SkillUpdate(BaseModel):
    """Request model for updating a skill."""
    name: Optional[str] = None
    role_title: Optional[str] = None
    role_description: Optional[str] = None
    expertise_areas: Optional[List[str]] = None
    primary_responsibilities: Optional[List[str]] = None
    secondary_responsibilities: Optional[List[str]] = None
    required_tools: Optional[List[str]] = None
    optional_tools: Optional[List[str]] = None
    tags: Optional[List[str]] = None
    priority: Optional[SkillPriority] = None
    category: Optional[SkillCategory] = None
    status: Optional[SkillStatus] = None
    token_budget: Optional[int] = None


class Skill(BaseModel):
    """
    Skill entity for storage and retrieval.

    This is the main model used for CRUD operations on skills.
    """
    id: UUID = Field(default_factory=uuid4, description="Skill ID")
    name: str = Field(..., description="Skill name")
    status: SkillStatus = Field(default=SkillStatus.DRAFT)
    definition: SkillDefinition = Field(..., description="Full skill definition")
    raw_content: Optional[str] = Field(None, description="Raw skill file content (YAML)")
    agent_id: Optional[UUID] = Field(None, description="Associated agent ID")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        from_attributes = True


# =============================================================================
# Validation Models
# =============================================================================

class ValidationSeverity(str, Enum):
    """Severity level for validation issues."""
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


class ValidationIssue(BaseModel):
    """A single validation issue."""
    severity: ValidationSeverity
    code: str = Field(..., description="Issue code (e.g., 'MISSING_SECTION')")
    message: str = Field(..., description="Human-readable message")
    path: Optional[str] = Field(None, description="Path to the problematic field")
    suggestion: Optional[str] = Field(None, description="Suggestion for fixing")


class SkillValidationResult(BaseModel):
    """
    Result of skill file validation.

    Contains validation status and any issues found during validation.
    """
    is_valid: bool = Field(..., description="Whether the skill is valid")
    skill_id: Optional[UUID] = Field(None, description="Skill ID if available")
    skill_name: Optional[str] = Field(None, description="Skill name if available")
    schema_version: str = Field(default="1.0.0", description="Schema version used")
    issues: List[ValidationIssue] = Field(default_factory=list)
    warnings_count: int = Field(default=0)
    errors_count: int = Field(default=0)
    validated_at: datetime = Field(default_factory=datetime.utcnow)

    @classmethod
    def success(cls, skill_id: Optional[UUID] = None, skill_name: Optional[str] = None) -> "SkillValidationResult":
        """Create a successful validation result."""
        return cls(
            is_valid=True,
            skill_id=skill_id,
            skill_name=skill_name,
        )

    @classmethod
    def failure(
        cls,
        issues: List[ValidationIssue],
        skill_id: Optional[UUID] = None,
        skill_name: Optional[str] = None
    ) -> "SkillValidationResult":
        """Create a failed validation result."""
        errors = sum(1 for i in issues if i.severity == ValidationSeverity.ERROR)
        warnings = sum(1 for i in issues if i.severity == ValidationSeverity.WARNING)
        return cls(
            is_valid=errors == 0,
            skill_id=skill_id,
            skill_name=skill_name,
            issues=issues,
            errors_count=errors,
            warnings_count=warnings,
        )


# =============================================================================
# Generation Models
# =============================================================================

class SkillGenerationRequest(BaseModel):
    """Request for generating a skill from role responsibilities."""
    role_title: str = Field(..., description="Title of the role")
    role_description: str = Field(..., description="Description of the role")
    responsibilities: List[str] = Field(..., description="List of responsibilities")
    expertise_areas: Optional[List[str]] = Field(None, description="Areas of expertise")
    target_agent_type: Optional[str] = Field(None, description="Target agent type")
    priority: SkillPriority = Field(default=SkillPriority.MEDIUM)
    category: SkillCategory = Field(default=SkillCategory.TECHNICAL)
    include_examples: bool = Field(default=True, description="Generate examples")
    include_procedures: bool = Field(default=True, description="Generate procedures")
    max_token_budget: int = Field(default=2000, description="Max token budget")


class SkillGenerationResponse(BaseModel):
    """Response from skill generation."""
    success: bool
    skill: Optional[Skill] = None
    raw_content: Optional[str] = None
    validation_result: Optional[SkillValidationResult] = None
    generation_metadata: Dict[str, Any] = Field(default_factory=dict)
    error: Optional[str] = None


# =============================================================================
# Optimization Models
# =============================================================================

class OptimizationStrategy(str, Enum):
    """Strategy for skill optimization."""
    TOKEN_REDUCTION = "token_reduction"  # Reduce token count
    PRIORITY_LOADING = "priority_loading"  # Load based on priority
    CONTEXT_AWARE = "context_aware"  # Load based on current context
    MINIMAL = "minimal"  # Load minimal viable skill set


class SkillOptimizationRequest(BaseModel):
    """Request for skill optimization."""
    skill_ids: List[UUID] = Field(..., description="Skills to optimize")
    strategy: OptimizationStrategy = Field(default=OptimizationStrategy.TOKEN_REDUCTION)
    target_token_budget: int = Field(default=4000, description="Target total tokens")
    preserve_sections: List[str] = Field(default_factory=list, description="Sections to preserve")
    context: Optional[str] = Field(None, description="Current context for context-aware loading")


class SkillOptimizationResult(BaseModel):
    """Result of skill optimization."""
    success: bool
    original_token_count: int
    optimized_token_count: int
    reduction_percentage: float
    optimized_skills: List[Skill] = Field(default_factory=list)
    dropped_skills: List[UUID] = Field(default_factory=list)
    optimization_details: Dict[str, Any] = Field(default_factory=dict)
